[package]
name = "recieved"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
iced = { version = "0.10", features = ["smol"] }
serialport = "4.2"
reed-solomon = "0.2"
rfd = "0.10"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
futures = "0.3" 
